/**
 * Extract metadata from the Diplomacy standard.svg and generate:
 * 1. web/src/lib/map-metadata.ts - typed coordinate/size/color constants
 * 2. web/public/standard-base.svg - cleaned SVG for rendering
 *
 * Run with: bun run web/scripts/extract-svg-metadata.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";

const ROOT = resolve(import.meta.dir, "../..");
const SVG_PATH = resolve(
  ROOT,
  "src/rlm_diplomacy/_vendor/diplomacy/maps/svg/standard.svg",
);
const META_OUT = resolve(ROOT, "web/src/lib/map-metadata.ts");
const SVG_OUT = resolve(ROOT, "web/public/standard-base.svg");

// Ensure output dirs exist
mkdirSync(dirname(META_OUT), { recursive: true });
mkdirSync(dirname(SVG_OUT), { recursive: true });

const svg = readFileSync(SVG_PATH, "utf-8");

// ---------------------------------------------------------------------------
// 1. Extract province coordinates
// ---------------------------------------------------------------------------
interface RawCoord {
  unit: [number, number];
  disl: [number, number];
}

const provinces: Record<string, RawCoord> = {};
const provRe =
  /<jdipNS:PROVINCE\s+name="([^"]+)">\s*<jdipNS:UNIT\s+x="([^"]+)"\s+y="([^"]+)"\/>\s*<jdipNS:DISLODGED_UNIT\s+x="([^"]+)"\s+y="([^"]+)"\/>\s*<\/jdipNS:PROVINCE>/g;

let m: RegExpExecArray | null;
while ((m = provRe.exec(svg)) !== null) {
  // Convert name from lowercase-dash to uppercase-slash
  const rawName = m[1]; // e.g. "bul-ec"
  const name = rawName.toUpperCase().replace(/-/g, "/");
  provinces[name] = {
    unit: [parseFloat(m[2]), parseFloat(m[3])],
    disl: [parseFloat(m[4]), parseFloat(m[5])],
  };
}

console.log(`Extracted ${Object.keys(provinces).length} province coordinates`);

// ---------------------------------------------------------------------------
// 2. Extract symbol sizes
// ---------------------------------------------------------------------------
interface SymSize {
  width: number;
  height: number;
}

const symbolSizes: Record<string, SymSize> = {};
const symRe =
  /<jdipNS:SYMBOLSIZE\s+name="([^"]+)"\s+width="([^"]+)"\s+height="([^"]+)"\/>/g;

while ((m = symRe.exec(svg)) !== null) {
  symbolSizes[m[1]] = {
    width: parseFloat(m[2]),
    height: parseFloat(m[3]),
  };
}

console.log(`Extracted ${Object.keys(symbolSizes).length} symbol sizes`);

// ---------------------------------------------------------------------------
// 3. Extract power colors
// ---------------------------------------------------------------------------
const powerColors: Record<string, string> = {};
const colorRe =
  /<jdipNS:POWERCOLOR\s+power="([^"]+)"\s+color="([^"]+)"\/>/g;

while ((m = colorRe.exec(svg)) !== null) {
  powerColors[m[1].toUpperCase()] = m[2];
}

console.log(`Extracted ${Object.keys(powerColors).length} power colors`);

// ---------------------------------------------------------------------------
// 4. Generate map-metadata.ts
// ---------------------------------------------------------------------------
const sortedProvinces = Object.keys(provinces).sort();
const coordEntries = sortedProvinces
  .map((k) => {
    const p = provinces[k];
    return `  "${k}": { unit: [${p.unit[0]}, ${p.unit[1]}], disl: [${p.disl[0]}, ${p.disl[1]}] }`;
  })
  .join(",\n");

const symEntries = Object.keys(symbolSizes)
  .sort()
  .map((k) => {
    const s = symbolSizes[k];
    return `  ${k}: { width: ${s.width}, height: ${s.height} }`;
  })
  .join(",\n");

const colorEntries = Object.keys(powerColors)
  .sort()
  .map((k) => `  ${k}: "${powerColors[k]}"`)
  .join(",\n");

const tsContent = `// Auto-generated by scripts/extract-svg-metadata.ts — do not edit manually

export interface ProvinceCoord {
  unit: [number, number];
  disl: [number, number];
}

export const Coordinates: Record<string, ProvinceCoord> = {
${coordEntries},
};

export const SymbolSizes: Record<string, { width: number; height: number }> = {
${symEntries},
};

export const PowerColors: Record<string, string> = {
${colorEntries},
};
`;

writeFileSync(META_OUT, tsContent, "utf-8");
console.log(`Wrote ${META_OUT}`);

// ---------------------------------------------------------------------------
// 5. Generate cleaned SVG
// ---------------------------------------------------------------------------
let cleaned = svg;

// Remove jdipNS:DISPLAY block
cleaned = cleaned.replace(
  /\s*<jdipNS:DISPLAY>[\s\S]*?<\/jdipNS:DISPLAY>/,
  "",
);

// Remove jdipNS:ORDERDRAWING block
cleaned = cleaned.replace(
  /\s*<jdipNS:ORDERDRAWING>[\s\S]*?<\/jdipNS:ORDERDRAWING>/,
  "",
);

// Remove jdipNS:PROVINCE_DATA block
cleaned = cleaned.replace(
  /\s*<jdipNS:PROVINCE_DATA>[\s\S]*?<\/jdipNS:PROVINCE_DATA>/,
  "",
);

// Empty UnitLayer content (keep the <g> tag)
cleaned = cleaned.replace(
  /<g id="UnitLayer"[\s\S]*?(?:<\/g>|\/>)/,
  '<g id="UnitLayer"/>',
);

// Empty DislodgedUnitLayer content
cleaned = cleaned.replace(
  /<g id="DislodgedUnitLayer"[\s\S]*?(?:<\/g>|\/>)/,
  '<g id="DislodgedUnitLayer"/>',
);

// Empty OrderLayer's Layer1 and Layer2 sub-groups
cleaned = cleaned.replace(
  /(<g id="OrderLayer">)\s*<g id="Layer2"[\s\S]*?(?:<\/g>|\/>)\s*<g id="Layer1"[\s\S]*?(?:<\/g>|\/>)/,
  '$1\n        <g id="Layer2"/>\n        <g id="Layer1"/>',
);

// Remove xmlns:jdipNS attribute since we stripped all jdipNS elements
cleaned = cleaned.replace(/\s*xmlns:jdipNS="[^"]*"/, "");

writeFileSync(SVG_OUT, cleaned, "utf-8");
console.log(`Wrote ${SVG_OUT}`);
